In [1]:
import pandas as pd

#Comprabación.

ruta = 'C:/Users/OAD/Documents/lending_club_sql_risk/lending_dataset/loan.csv'

sample = pd.read_csv(ruta, nrows=1000)

print('Dimensiones de la muestra:', sample.shape)
print('Total de columnas:', len(sample.columns))

Dimensiones de la muestra: (1000, 145)
Total de columnas: 145

*Inspeccionamos columnas candidatas.*

In [2]:
#Comprobación de columnas.
columnas_deseadas = [
    'id', 'loan_amnt', 'funded_amnt', 'term', 'int_rate', 'grade', 'sub_grade', 'loan_status', 'annual_inc', 'emp_length', 'home_ownership',
     'dti', 'purpose', 'addr_state', 'fico_range_low', 'fico_range_high', 'delinq_2yrs', 'issue_d']
existen = [c for c in columnas_deseadas if c in sample.columns]
no_existen = [c for c in columnas_deseadas if c not in sample.columns]

print('Sí están:', existen)
print('No están:', no_existen)

Sí están: ['id', 'loan_amnt', 'funded_amnt', 'term', 'int_rate', 'grade', 'sub_grade', 'loan_status', 'annual_inc', 'emp_length', 'home_ownership', 'dti', 'purpose', 'addr_state', 'delinq_2yrs', 'issue_d']
No están: ['fico_range_low', 'fico_range_high']

In [3]:
fico_cols = [c for c in sample.columns if 'fico' in c.lower()]
print('Columnas con "fico":', fico_cols)

Columnas con "fico": []

*Columnas con informacion FICO no disponibles. Se procede a utilizar 'grade'.*

*Cargamos el dataset completo.*

In [4]:
#Carga y comprobación.
df = pd.read_csv(ruta, encoding='utf-8', sep=',') #Cargamos con encoding y separador ingles.

df.sample(15) #Muestra

C:\Users\OAD\AppData\Local\Temp\ipykernel_11480\1945525730.py:2: DtypeWarning: Columns (19,47,55,112,123,124,125,128,129,130,133,139,140,141) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(ruta, encoding='utf-8', sep=',') #Cargamos con encoding y separador ingles.

,id,member_id,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,sub_grade,...,hardship_payoff_balance_amount,hardship_last_payment_amount,disbursement_method,debt_settlement_flag,debt_settlement_flag_date,settlement_status,settlement_date,settlement_amount,settlement_percentage,settlement_term
1612170,NaN,NaN,31800,31800,31800.0,60 months,15.05,757.36,C,C4,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
91167,NaN,NaN,18000,18000,18000.0,60 months,29.69,578.94,F,F2,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
41522,NaN,NaN,15000,15000,15000.0,36 months,14.47,516.10,C,C2,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
62474,NaN,NaN,5000,5000,5000.0,36 months,20.89,188.10,D,D4,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
7820,NaN,NaN,6000,6000,6000.0,36 months,6.46,183.79,A,A1,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
1402829,NaN,NaN,40000,40000,40000.0,36 months,11.39,1316.95,B,B3,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
2021565,NaN,NaN,7525,7525,7525.0,36 months,12.49,251.71,B,B5,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
361480,NaN,NaN,12000,12000,12000.0,36 months,9.43,384.01,B,B1,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
55438,NaN,NaN,6500,6500,6500.0,36 months,16.91,231.46,C,C5,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
1411363,NaN,NaN,8400,8400,8400.0,36 months,8.24,264.16,B,B1,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
1827857,NaN,NaN,11500,11500,11500.0,36 months,11.14,377.26,B,B2,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
199788,NaN,NaN,12000,12000,12000.0,36 months,7.21,371.68,A,A3,...,NaN,NaN,DirectPay,N,NaN,NaN,NaN,NaN,NaN,NaN
1882723,NaN,NaN,33100,33100,33100.0,60 months,19.99,876.77,E,E3,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
36962,NaN,NaN,10000,10000,10000.0,36 months,10.33,324.23,B,B1,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
1254430,NaN,NaN,9000,9000,9000.0,36 months,7.89,281.58,A,A5,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
#Inspección inicial.
print('filas y columnas', df.shape)
print('-----------------------------')
print('Tipos de datos: ', df.dtypes)
print('-----------------------------')
print('Nulos', df.isnull().sum())
print('-----------------------------')
print('Muestra', df.sample(15))

filas y columnas (2260668, 145)
-----------------------------
Tipos de datos:  id                       float64
member_id                float64
loan_amnt                  int64
funded_amnt                int64
funded_amnt_inv          float64
                          ...
settlement_status         object
settlement_date           object
settlement_amount        float64
settlement_percentage    float64
settlement_term          float64
Length: 145, dtype: object
-----------------------------
Nulos id                       2260668
member_id                2260668
loan_amnt                      0
funded_amnt                    0
funded_amnt_inv                0
                          ...
settlement_status        2227612
settlement_date          2227612
settlement_amount        2227612
settlement_percentage    2227612
settlement_term          2227612
Length: 145, dtype: int64
-----------------------------
Muestra          id  member_id  loan_amnt  funded_amnt  funded_amnt_inv        term  \
1959262 NaN        NaN      20000        20000          20000.0   36 months
1791089 NaN        NaN      24000        24000          23925.0   60 months
1830091 NaN        NaN       3500         3500           3500.0   36 months
651036  NaN        NaN      10000        10000          10000.0   36 months
1883851 NaN        NaN      13225        13225          13225.0   36 months
283351  NaN        NaN      12000        12000          12000.0   60 months
112117  NaN        NaN      32000        32000          32000.0   60 months
31116   NaN        NaN      15000        15000          15000.0   36 months
1743995 NaN        NaN      35000        35000          35000.0   36 months
965431  NaN        NaN      18000        18000          18000.0   60 months
1440221 NaN        NaN      35000        35000          35000.0   36 months
1086471 NaN        NaN       9600         9600           9600.0   36 months
1881669 NaN        NaN      10000        10000          10000.0   36 months
1316563 NaN        NaN      10000        10000          10000.0   36 months
1031229 NaN        NaN       7000         7000           7000.0   36 months

         int_rate  installment grade sub_grade  ...  \
1959262     10.15       646.76     B        B2  ...
1791089     21.49       655.92     E        E3  ...
1830091     16.29       123.56     C        C4  ...
651036      11.47       329.62     B        B5  ...
1883851      9.49       423.58     B        B2  ...
283351      19.42       314.07     D        D3  ...
112117      12.73       723.69     B        B5  ...
31116        8.81       475.68     A        A5  ...
1743995     10.64      1139.90     B        B2  ...
965431      13.67       415.76     C        C4  ...
1440221     11.49      1154.00     B        B5  ...
1086471      8.18       301.63     B        B1  ...
1881669     12.39       334.01     C        C1  ...
1316563     14.31       343.29     C        C4  ...
1031229     12.29       233.48     C        C1  ...

        hardship_payoff_balance_amount hardship_last_payment_amount  \
1959262                            NaN                          NaN
1791089                            NaN                          NaN
1830091                            NaN                          NaN
651036                             NaN                          NaN
1883851                            NaN                          NaN
283351                             NaN                          NaN
112117                             NaN                          NaN
31116                              NaN                          NaN
1743995                            NaN                          NaN
965431                             NaN                          NaN
1440221                            NaN                          NaN
1086471                            NaN                          NaN
1881669                            NaN                          NaN
1316563                            NaN                          NaN
1031229                            NaN                          NaN

        disbursement_method  debt_settlement_flag debt_settlement_flag_date  \
1959262                Cash                     N                       NaN
1791089                Cash                     N                       NaN
1830091                Cash                     N                       NaN
651036                 Cash                     N                       NaN
1883851                Cash                     N                       NaN
283351                 Cash                     N                       NaN
112117                 Cash                     N                       NaN
31116                  Cash                     N                       NaN
1743995                Cash                     N                       NaN
965431                 Cash                     N                       NaN
1440221                Cash                     N                       NaN
1086471                Cash                     N                       NaN
1881669                Cash                     N                       NaN
1316563                Cash                     N                       NaN
1031229                Cash                     N                       NaN

        settlement_status settlement_date settlement_amount  \
1959262               NaN             NaN               NaN
1791089               NaN             NaN               NaN
1830091               NaN             NaN               NaN
651036                NaN             NaN               NaN
1883851               NaN             NaN               NaN
283351                NaN             NaN               NaN
112117                NaN             NaN               NaN
31116                 NaN             NaN               NaN
1743995               NaN             NaN               NaN
965431                NaN             NaN               NaN
1440221               NaN             NaN               NaN
1086471               NaN             NaN               NaN
1881669               NaN             NaN               NaN
1316563               NaN             NaN               NaN
1031229               NaN             NaN               NaN

         settlement_percentage settlement_term
1959262                    NaN             NaN
1791089                    NaN             NaN
1830091                    NaN             NaN
651036                     NaN             NaN
1883851                    NaN             NaN
283351                     NaN             NaN
112117                     NaN             NaN
31116                      NaN             NaN
1743995                    NaN             NaN
965431                     NaN             NaN
1440221                    NaN             NaN
1086471                    NaN             NaN
1881669                    NaN             NaN
1316563                    NaN             NaN
1031229                    NaN             NaN

[15 rows x 145 columns]

In [6]:
#Se añaden las columnas a el dataframe util.
columnas_df = [
    'id', 'loan_amnt', 'funded_amnt', 'term', 'int_rate', 'grade', 'sub_grade', 'loan_status', 'annual_inc', 'emp_length', 'home_ownership',
     'dti', 'purpose', 'addr_state', 'delinq_2yrs', 'issue_d']

df_a_limpiar = df[columnas_df]

*Limpieza oficial.*

In [7]:
#Inspección limpieza.
print('----------------filas y columnas--------------')
print(df_a_limpiar.shape)
print('-------------Tipos de datos----------------')
print(df_a_limpiar.dtypes)
print('------------Nulos------------')
print(df_a_limpiar.isnull().sum())

----------------filas y columnas--------------
(2260668, 16)
-------------Tipos de datos----------------
id                float64
loan_amnt           int64
funded_amnt         int64
term               object
int_rate          float64
grade              object
sub_grade          object
loan_status        object
annual_inc        float64
emp_length         object
home_ownership     object
dti               float64
purpose            object
addr_state         object
delinq_2yrs       float64
issue_d            object
dtype: object
------------Nulos------------
id                2260668
loan_amnt               0
funded_amnt             0
term                    0
int_rate                0
grade                   0
sub_grade               0
loan_status             0
annual_inc              4
emp_length         146907
home_ownership          0
dti                  1711
purpose                 0
addr_state              0
delinq_2yrs            29
issue_d                 0
dtype: int64

In [8]:
df_a_limpiar.sample(15)

,id,loan_amnt,funded_amnt,term,int_rate,grade,sub_grade,loan_status,annual_inc,emp_length,home_ownership,dti,purpose,addr_state,delinq_2yrs,issue_d
2255806,NaN,20000,20000,36 months,12.62,C,C1,Current,29000.0,10+ years,RENT,42.38,credit_card,CA,0.0,Oct-2017
1019844,NaN,25000,25000,60 months,22.99,F,F2,Fully Paid,72000.0,2 years,OWN,33.42,moving,AK,0.0,Oct-2015
151131,NaN,5000,5000,36 months,6.11,A,A1,Fully Paid,26000.0,NaN,RENT,5.40,credit_card,MI,0.0,Sep-2018
2126956,NaN,9000,9000,36 months,7.88,A,A5,Fully Paid,52500.0,4 years,MORTGAGE,4.18,home_improvement,MA,0.0,Jul-2010
1559163,NaN,10000,10000,36 months,9.93,B,B2,Fully Paid,40000.0,10+ years,OWN,27.59,debt_consolidation,TX,0.0,Jul-2017
1580487,NaN,26000,26000,36 months,7.97,A,A5,Current,62000.0,5 years,MORTGAGE,19.22,debt_consolidation,NY,0.0,Jun-2017
1432147,NaN,2250,2250,36 months,5.32,A,A1,Current,71000.0,2 years,MORTGAGE,15.28,medical,KY,0.0,Jan-2017
1634979,NaN,15000,15000,36 months,16.02,C,C5,Charged Off,66040.0,9 years,RENT,16.06,credit_card,AZ,0.0,May-2017
888891,NaN,32000,32000,36 months,11.44,B,B4,Current,110000.0,10+ years,MORTGAGE,12.12,debt_consolidation,FL,0.0,Nov-2016
587768,NaN,30500,30500,36 months,7.99,A,A4,Fully Paid,107000.0,5 years,MORTGAGE,13.78,debt_consolidation,NJ,0.0,Jul-2016
1914513,NaN,11000,11000,36 months,8.39,A,A5,Fully Paid,80000.0,10+ years,MORTGAGE,8.78,debt_consolidation,KS,0.0,Oct-2014
1543538,NaN,6000,6000,36 months,5.32,A,A1,Fully Paid,68000.0,10+ years,RENT,13.13,debt_consolidation,NY,0.0,Jul-2017
2222611,NaN,11000,11000,36 months,16.02,C,C5,Current,66000.0,10+ years,MORTGAGE,33.65,debt_consolidation,TX,0.0,Oct-2017
2053918,NaN,16000,16000,60 months,18.92,D,D4,Charged Off,50000.0,10+ years,MORTGAGE,19.83,credit_card,MA,0.0,Apr-2014
1445610,NaN,2000,2000,36 months,13.99,C,C3,Fully Paid,42000.0,10+ years,RENT,18.80,debt_consolidation,NY,1.0,Jan-2017

*Se descarta el uso de 'id' como identificador. Se hipotiza que los nulos se deben por motivos de privacidad, esto se concluye al contemplar que el dataset contiene datos reales de LendingClub.*

In [9]:
#Se reasignan las columnas al dataframe.
columnas_df = [
    'loan_amnt', 'funded_amnt', 'term', 'int_rate', 'grade', 'sub_grade', 'loan_status', 'annual_inc', 'emp_length', 'home_ownership',
    'dti', 'purpose', 'addr_state', 'delinq_2yrs', 'issue_d']

df_a_limpiar = df[columnas_df]
df_a_limpiar.sample(10)

,loan_amnt,funded_amnt,term,int_rate,grade,sub_grade,loan_status,annual_inc,emp_length,home_ownership,dti,purpose,addr_state,delinq_2yrs,issue_d
2020867,8250,8250,36 months,8.39,A,A5,Fully Paid,55000.0,4 years,MORTGAGE,18.48,debt_consolidation,CO,0.0,May-2014
182441,5000,5000,36 months,10.08,B,B1,Current,65000.0,6 years,RENT,15.51,credit_card,AZ,1.0,Aug-2018
770736,12000,12000,36 months,5.32,A,A1,Fully Paid,118500.0,< 1 year,MORTGAGE,13.35,debt_consolidation,CO,0.0,Feb-2016
279251,35000,35000,36 months,5.31,A,A1,Current,224000.0,10+ years,MORTGAGE,31.95,debt_consolidation,NY,0.0,Jun-2018
191450,15000,15000,36 months,6.11,A,A1,Current,50000.0,< 1 year,MORTGAGE,24.94,debt_consolidation,GA,0.0,Aug-2018
415113,11000,11000,36 months,5.31,A,A1,Current,45000.0,6 years,RENT,18.10,credit_card,OH,0.0,Mar-2018
1690640,10000,10000,36 months,15.10,C,C2,Charged Off,45000.0,6 years,MORTGAGE,24.77,debt_consolidation,GA,3.0,Dec-2013
2149219,16000,16000,60 months,13.59,C,C2,Current,72000.0,7 years,RENT,32.28,debt_consolidation,TX,1.0,Dec-2017
932174,10000,10000,36 months,8.49,B,B1,Fully Paid,120000.0,10+ years,MORTGAGE,35.56,credit_card,CT,0.0,Dec-2015
1872231,10000,10000,60 months,8.67,B,B1,Current,85000.0,10+ years,RENT,13.70,debt_consolidation,NY,0.0,Dec-2014

*Entendiendo las columnas:*

## LendingClub Dataset — Documentación de Columnas

### Préstamo (Loan)
| Columna | Descripción |
|---------|-------------|
| `loan_amnt` | Monto solicitado por el prestatario (principal requested) |
| `funded_amnt` | Monto realmente financiado (puede ser < que loan_amnt) |
| `term` | Plazo del préstamo: 36 o 60 meses |
| `issue_d` | Fecha de emisión del préstamo |

### Riesgo (Risk)
| Columna | Descripción |
|---------|-------------|
| `int_rate` | Tasa de interés anual (0.1299 = 12.99%) |
| `grade` | Calificación general de riesgo: A=mejor, G=peor |
| `sub_grade` | Calificación más fina: A1-A5, B1-B5, ..., G5 |
| `loan_status` | **Estado del préstamo: Fully Paid, Charged Off (defaulteó), Current, Late** ⭐ TARGET |

### Prestatario (Borrower)
| Columna | Descripción |
|---------|-------------|
| `annual_inc` | Ingreso anual auto-reportado en USD |
| `emp_length` | Años de antigüedad laboral: 0=<1 año, 10=10+ años |
| `home_ownership` | Tipo de vivienda: RENT, OWN, MORTGAGE, OTHER |
| `addr_state` | Estado/provincia de residencia (códigos 2 letras) |

### Crédito & Deuda (Credit)
| Columna | Descripción |
|---------|-------------|
| `dti` | Debt-to-income ratio: (pagos mensuales deuda) / (ingreso mensual). LC acepta si < 35% |
| `delinq_2yrs` | Número de veces 30+ días en mora en últimos 2 años. 0=nunca |

In [10]:
print('------------Nulos------------')
print(df_a_limpiar.isnull().sum())

------------Nulos------------
loan_amnt              0
funded_amnt            0
term                   0
int_rate               0
grade                  0
sub_grade              0
loan_status            0
annual_inc             4
emp_length        146907
home_ownership         0
dti                 1711
purpose                0
addr_state             0
delinq_2yrs           29
issue_d                0
dtype: int64

*Se hipotiza que 'emp_length' figura con tal cantidad de nulos por el dato incluyente de signos como ">, <, +, etc". Lo que para python es un string y no un object. Se procede a comprobar.*

In [11]:
print(df_a_limpiar['emp_length'].dropna().nunique()) #Cantidad de las variables sin nulos.
print('---')
print(df_a_limpiar['emp_length'].value_counts(dropna=False)) #Cualidad de las variables con nulos (NaN).

11
---
emp_length
10+ years    748005
2 years      203677
< 1 year     189988
3 years      180753
1 year       148403
NaN          146907
5 years      139698
4 years      136605
6 years      102628
7 years       92695
8 years       91914
9 years       79395
Name: count, dtype: int64

*Se confirma presencia de strings en una columna tipo floar. Tambien se observan nulos reales dentro de la columna. Se procede a remapear columna 'emp_length' y limpar nulos.*

In [12]:
df_a_limpiar = df_a_limpiar.dropna(subset=['emp_length']) #Descarte de nulos.

emp_length_map = { #Remapeo.
    '< 1 year': 0,
    '1 year': 1,
    '2 years': 2,
    '3 years': 3,
    '4 years': 4,
    '5 years': 5,
    '6 years': 6,
    '7 years': 7,
    '8 years': 8,
    '9 years': 9,
    '10+ years': 10,
}
df_a_limpiar['emp_length'] = df_a_limpiar['emp_length'].map(emp_length_map)

In [13]:
#Comprobación.
print(df_a_limpiar['emp_length'].dropna().nunique()) #Cantidad de las variables.
print('---')
print(df_a_limpiar['emp_length'].value_counts()) #Cualidad de las variables.

11
---
emp_length
10    748005
2     203677
0     189988
3     180753
1     148403
5     139698
4     136605
6     102628
7      92695
8      91914
9      79395
Name: count, dtype: int64

*Nulos descartados satisfactoriamente.*

In [14]:
#Tipo de dato.
df_a_limpiar['emp_length'] = df_a_limpiar['emp_length'].astype(int)
print(df_a_limpiar['emp_length'].dtype)

int64

In [15]:
#Comprobación de nulos.
print('------------Nulos------------')
print(df_a_limpiar.isnull().sum())
print('-----------Filas actuales------------')
print(df_a_limpiar.shape[0])

------------Nulos------------
loan_amnt           0
funded_amnt         0
term                0
int_rate            0
grade               0
sub_grade           0
loan_status         0
annual_inc          4
emp_length          0
home_ownership      0
dti               113
purpose             0
addr_state          0
delinq_2yrs        29
issue_d             0
dtype: int64
-----------Filas actuales------------
2113761

*Dada la baja cantidad de nulos, se procede a descartar 'annual_inc' y 'dti'. 'delinq_2yrs' Se inspecciona dada la probabilidad de que '0' sea considerado nulo.*

In [16]:
#Porcentaje de nulos descartados
print('-----Porcentaje de nulos descartados en "annual_inc"-----')
print(round(df_a_limpiar['annual_inc'].isna().sum()/df_a_limpiar.shape[0] * 100, 6),'%')
#Porcentaje de nulos descartados
print('-----Porcentaje de nulos descartados en "dti"-----')
print(round(df_a_limpiar['dti'].isna().sum()/df_a_limpiar.shape[0] * 100, 6),'%')

-----Porcentaje de nulos descartados en "annual_inc"-----
0.000189 %
-----Porcentaje de nulos descartados en "dti"-----
0.005346 %

In [17]:
df_a_limpiar = df_a_limpiar.dropna(subset=['annual_inc', 'dti'])
#Comprobación de nulos.
print('------------Nulos------------')
print(df_a_limpiar.isnull().sum())
print('-----------Filas actuales------------')
print(df_a_limpiar.shape[0])

------------Nulos------------
loan_amnt          0
funded_amnt        0
term               0
int_rate           0
grade              0
sub_grade          0
loan_status        0
annual_inc         0
emp_length         0
home_ownership     0
dti                0
purpose            0
addr_state         0
delinq_2yrs       25
issue_d            0
dtype: int64
-----------Filas actuales------------
2113644

*Se inspecciona 'delinq_2_years'.*

In [18]:
#Inspección nulos menores.
print('-----delinq_2yrs nulos-------')
print(df_a_limpiar['delinq_2yrs'].isna().sum())
print('-----Inspección visual-------')
df_a_limpiar[df_a_limpiar['delinq_2yrs'].isna()][['loan_amnt', 'grade', 'loan_status', 'annual_inc', 'dti', 'delinq_2yrs']]

-----delinq_2yrs nulos-------
25
-----Inspección visual-------

,loan_amnt,grade,loan_status,annual_inc,dti,delinq_2yrs
2141944,4350,A,Does not meet the credit policy. Status:Fully ...,120000.0,4.00,NaN
2141957,3900,B,Does not meet the credit policy. Status:Fully ...,98000.0,10.00,NaN
2141968,3200,B,Does not meet the credit policy. Status:Fully ...,150000.0,10.00,NaN
2141979,7200,C,Does not meet the credit policy. Status:Fully ...,95000.0,10.00,NaN
2141994,1900,B,Does not meet the credit policy. Status:Fully ...,100000.0,10.00,NaN
2141999,1200,B,Does not meet the credit policy. Status:Fully ...,36000.0,3.27,NaN
2142000,5000,C,Does not meet the credit policy. Status:Fully ...,28000.0,3.51,NaN
2142001,1400,C,Does not meet the credit policy. Status:Fully ...,40000.0,8.61,NaN
2142002,1000,E,Does not meet the credit policy. Status:Fully ...,25000.0,16.27,NaN
2142003,5000,A,Does not meet the credit policy. Status:Fully ...,300000.0,5.38,NaN
2142004,2500,A,Does not meet the credit policy. Status:Fully ...,66624.0,10.36,NaN
2142005,3000,A,Does not meet the credit policy. Status:Fully ...,80000.0,0.39,NaN
2142006,2600,A,Does not meet the credit policy. Status:Charge...,6500.0,6.46,NaN
2142007,1000,A,Does not meet the credit policy. Status:Fully ...,50000.0,1.10,NaN
2142008,6450,C,Does not meet the credit policy. Status:Fully ...,32000.0,10.00,NaN
2142009,1275,D,Does not meet the credit policy. Status:Charge...,40000.0,10.00,NaN
2142010,10500,C,Does not meet the credit policy. Status:Fully ...,60000.0,19.50,NaN
2142011,3000,B,Does not meet the credit policy. Status:Fully ...,35000.0,10.00,NaN
2142012,3000,B,Does not meet the credit policy. Status:Fully ...,20000.0,10.00,NaN
2142013,2000,B,Does not meet the credit policy. Status:Fully ...,6000.0,10.00,NaN
2142014,6500,B,Does not meet the credit policy. Status:Charge...,20000.0,10.00,NaN
2142015,3500,C,Does not meet the credit policy. Status:Fully ...,180000.0,10.00,NaN
2142016,1000,B,Does not meet the credit policy. Status:Fully ...,12000.0,10.00,NaN
2142017,2525,B,Does not meet the credit policy. Status:Fully ...,110000.0,10.00,NaN
2142019,5000,A,Does not meet the credit policy. Status:Fully ...,70000.0,8.81,NaN

*Se observa que un valor nulo en 'delinq_2yrs' está correlacionado con que 'loan_status' tenga como entrada:'Does not meet the credit policy. Status:Fully ...'.*

In [19]:
mask = df_a_limpiar['loan_status'].str.contains('Does not meet', na=False)
print(df_a_limpiar[mask]['loan_status'].value_counts())
print('-----Cantidades de "Does not meet"-----')
print('Total de "Does not meet":', mask.sum())
print('Total de nulos por "Does not meet":',df_a_limpiar['delinq_2yrs'].isna().sum())

loan_status
Does not meet the credit policy. Status:Fully Paid     1965
Does not meet the credit policy. Status:Charged Off     746
Name: count, dtype: int64
-----Cantidades de "Does not meet"-----
Total de "Does not meet": 2711
Total de nulos por "Does not meet": 25

*Se observa que no todos los 'Does not meet' estan relacionados a nulos. Se concluye que los valores nulos de 'delinq_2yrs' deben ser reemplazados por un valor inefectivo.*

In [20]:
df_a_limpiar['delinq_2yrs'] = df_a_limpiar['delinq_2yrs'].fillna(0)
#Inspección nulos.
print('-----delinq_2yrs nulos-------')
print(df_a_limpiar['delinq_2yrs'].isna().sum())
print('-----nulos-------')
print(df_a_limpiar.isna().sum())

-----delinq_2yrs nulos-------
0
-----nulos-------
loan_amnt         0
funded_amnt       0
term              0
int_rate          0
grade             0
sub_grade         0
loan_status       0
annual_inc        0
emp_length        0
home_ownership    0
dti               0
purpose           0
addr_state        0
delinq_2yrs       0
issue_d           0
dtype: int64

*Tabla limpiada de nulos satisfactoriamente.*

*Se proceden a verificar y reasignar dtypes.*

In [21]:
df_a_limpiar.dtypes

loan_amnt           int64
funded_amnt         int64
term               object
int_rate          float64
grade              object
sub_grade          object
loan_status        object
annual_inc        float64
emp_length          int64
home_ownership     object
dti               float64
purpose            object
addr_state         object
delinq_2yrs       float64
issue_d            object
dtype: object

In [22]:
#Cambio de dtypes.
df_a_limpiar['delinq_2yrs'] = df_a_limpiar['delinq_2yrs'].astype(int) #'delinq_2yrs' a int
print('delinq_2yrs:', df_a_limpiar['delinq_2yrs'].dtype)
df_a_limpiar['issue_d'] = pd.to_datetime(df_a_limpiar['issue_d'], format='%b-%Y') #'issue_d' a datetime
print('issue_d:', df_a_limpiar['issue_d'].dtype)
df_a_limpiar['term'] = df_a_limpiar['term'].str.extract('(\d+)').astype(int) #term a int (Solo el numero de meses de 'term')
print('term:', df_a_limpiar['term'].dtype)

delinq_2yrs: int64
issue_d: datetime64[ns]
term: int64

*Dtypes cambiados a su formato util.*

*Comprobamos outliers

*Resumen*

In [23]:
print('-----RESUMEN-----')
print()
print('-----Dimensiones-----')
print('Filas:', df_a_limpiar.shape[0])
print('Columnas:', df_a_limpiar.shape[1])
print()
print('-----Tipos de datos-----')
print(df_a_limpiar.dtypes)
print()
print('-----Nulos-----')
print(df_a_limpiar.isna().sum())
print()
print('-----Sample-----')
(df_a_limpiar.sample(10))

-----RESUMEN-----

-----Dimensiones-----
Filas: 2113644
Columnas: 15

-----Tipos de datos-----
loan_amnt                  int64
funded_amnt                int64
term                       int64
int_rate                 float64
grade                     object
sub_grade                 object
loan_status               object
annual_inc               float64
emp_length                 int64
home_ownership            object
dti                      float64
purpose                   object
addr_state                object
delinq_2yrs                int64
issue_d           datetime64[ns]
dtype: object

-----Nulos-----
loan_amnt         0
funded_amnt       0
term              0
int_rate          0
grade             0
sub_grade         0
loan_status       0
annual_inc        0
emp_length        0
home_ownership    0
dti               0
purpose           0
addr_state        0
delinq_2yrs       0
issue_d           0
dtype: int64

-----Sample-----

,loan_amnt,funded_amnt,term,int_rate,grade,sub_grade,loan_status,annual_inc,emp_length,home_ownership,dti,purpose,addr_state,delinq_2yrs,issue_d
1262825,35000,35000,60,13.99,C,C4,Fully Paid,155000.0,10,MORTGAGE,18.70,debt_consolidation,NC,4,2015-04-01
368585,10000,10000,36,6.07,A,A2,Current,120000.0,9,RENT,5.65,moving,NY,0,2018-04-01
682282,12000,12000,36,13.67,C,C3,Current,85000.0,6,MORTGAGE,9.01,debt_consolidation,CA,0,2016-04-01
2060369,20800,20800,60,25.80,G,G1,Fully Paid,67000.0,10,RENT,17.09,debt_consolidation,TX,0,2014-03-01
62327,20000,20000,36,6.11,A,A1,Current,90000.0,10,OWN,29.64,debt_consolidation,AL,0,2018-11-01
1752238,10000,10000,36,16.78,C,C5,Fully Paid,48700.0,8,RENT,28.95,debt_consolidation,TX,0,2013-07-01
259039,7500,7500,36,8.08,A,A5,Current,65000.0,0,RENT,9.14,debt_consolidation,OR,0,2018-06-01
352809,8000,8000,36,10.90,B,B4,Fully Paid,100442.0,10,MORTGAGE,20.85,debt_consolidation,CA,0,2018-04-01
1555731,19200,19200,36,19.03,D,D3,Fully Paid,71700.0,10,OWN,15.88,debt_consolidation,NY,0,2017-07-01
176135,35000,35000,36,6.11,A,A1,Current,75000.0,10,MORTGAGE,23.14,debt_consolidation,GA,0,2018-08-01

*Descarte de contenido inutil.*

*Se indaga sobre la columna 'loan_status'.*

In [24]:
df_a_limpiar['loan_status'].value_counts()

loan_status
Fully Paid                                             986880
Current                                                851120
Charged Off                                            241259
Late (31-120 days)                                      19962
In Grace Period                                          8378
Late (16-30 days)                                        3306
Does not meet the credit policy. Status:Fully Paid       1965
Does not meet the credit policy. Status:Charged Off       746
Default                                                    28
Name: count, dtype: int64

*Se decarta las entradas con 'loan_status' sin resultado definitivo (Pagado o incobrable). Dado que el objetivo es saber que predice que un prestamo caiga en mora, se deben descartar aquellos casos que no aporten información concreta. Tambien se reasignan variables para prestamos pagados y no pagados (good y bad) y se empieza con una nueva tabla.*

In [25]:
good = ['Fully Paid', 'Does not meet the credit policy. Status:Fully Paid'] #Pagados.
bad = ['Charged Off', 'Does not meet the credit policy. Status:Charged Off'] #Incobrables.

df_modelo = df_a_limpiar[df_a_limpiar['loan_status'].isin(good + bad)].copy() #Excluimos todo lo que no necesitamos.
df_modelo['default'] = df_modelo['loan_status'].isin(bad).astype(int) #Asignamos valor a la nueva columna 'default'.

print(df_modelo['default'].value_counts())
print('Filas: ',df_modelo.shape[0])
print(f'Tasa de default:  {df_modelo['default'].mean():.1%}')

default
0    988845
1    242005
Name: count, dtype: int64
Filas:  1230850
Tasa de default:  19.7%

*Se chequean valores atipicos en columnas 'dti' y 'annual_inc' porque se entiende que 'annual_inc' es un dato que el mismo cliente dio, y 'dti' es un resultado en donde 'annual_inc' fue utilizado en la ecuación.*

In [26]:
print('-----annual_inc-----')
print(df_modelo['annual_inc'].describe().apply(lambda x: f'{x:,.2f}'))
print('-----dti-----')
print(df_modelo['dti'].describe().apply(lambda x: f'{x:,.2f}'))

-----annual_inc-----
count     1,230,850.00
mean         77,775.63
std          71,193.30
min              33.00
25%          48,000.00
50%          65,000.00
75%          92,000.00
max      10,999,200.00
Name: annual_inc, dtype: object
-----dti-----
count    1,230,850.00
mean            18.10
std              9.40
min             -1.00
25%             11.74
50%             17.51
75%             23.88
max            999.00
Name: dti, dtype: object

*Se investigan valores atipicos.*

In [27]:
print('annual_inc > 1M: ', (df_modelo['annual_inc'] > 1_000_000).sum()) #excluimos ingresos anuales mayor a 1M. Si bien pueden ser reales, no son objetivo de prestamos. 
print('annual_inc < 1K: ', (df_modelo['annual_inc'] < 1_000).sum()) #excluimos ingresos anuales menores a 1K. Ingresos menores se atribuyen a error de formato o de entrada.
print('dti negativo: ', (df_modelo['dti'] < 0).sum()) #dti es un porcentaje de LendingClub. No puede ser menor a 0.
print('dti > 100: ', (df_modelo['dti'] > 100).sum()) #dti es un porcentaje de LendingClub. No puede ser mayor a 100.

annual_inc > 1M:  274
annual_inc < 1K:  7
dti negativo:  2
dti > 100:  245

*Se sospecha correlación.*

In [28]:
ingreso_alto = df_modelo['annual_inc'] > 1_000_000
dti_alto = df_modelo['dti'] > 100

print('Filas con ambos problemas: ', (ingreso_alto & dti_alto).sum())
print('Filas con ingreso alto: ', (ingreso_alto & -dti_alto).sum())
print('Filas con dti alto: ', (dti_alto &  -ingreso_alto).sum())

Filas con ambos problemas:  0
Filas con ingreso alto:  274
Filas con dti alto:  245

*Se descarta correlación comprobando solapamiento. Se procede a descartar outliers.*

In [29]:
#Quitamos outliers.
df_modelo = df_modelo[
    (df_modelo['annual_inc'] <= 1_000_000) &
    (df_modelo['annual_inc'] >= 1000) &
    (df_modelo['dti'] >= 0) &
    (df_modelo['dti'] <= 100)
].copy()

print('-----Filas post-limpieza de outliers-----')
print(df_modelo.shape[0])
print('-----annual_inc-----')
print(df_modelo['annual_inc'].describe().apply(lambda x: f'{x:,.2f}'))
print('-----dti-----')
print(df_modelo['dti'].describe().apply(lambda x: f'{x:,.2f}'))

-----Filas post-limpieza de outliers-----
1230327
-----annual_inc-----
count    1,230,327.00
mean        77,229.75
std         50,262.41
min          1,896.00
25%         48,000.00
50%         65,000.00
75%         92,000.00
max      1,000,000.00
Name: annual_inc, dtype: object
-----dti-----
count    1,230,327.00
mean            18.06
std              8.54
min              0.00
25%             11.75
50%             17.51
75%             23.88
max             99.92
Name: dti, dtype: object

In [30]:
df_modelo.sample(10)

,loan_amnt,funded_amnt,term,int_rate,grade,sub_grade,loan_status,annual_inc,emp_length,home_ownership,dti,purpose,addr_state,delinq_2yrs,issue_d,default
1554556,6000,6000,36,10.42,B,B3,Fully Paid,65000.0,9,MORTGAGE,15.29,debt_consolidation,KY,0,2017-07-01,0
1086789,8000,8000,36,8.18,B,B1,Fully Paid,34000.0,10,RENT,7.66,credit_card,DE,1,2015-09-01,0
1896049,9550,9550,36,18.24,D,D5,Fully Paid,30000.0,10,MORTGAGE,33.12,debt_consolidation,NV,0,2014-11-01,0
1028299,16000,16000,36,12.69,C,C2,Fully Paid,72000.0,4,RENT,10.15,debt_consolidation,NC,0,2015-10-01,0
537963,18500,18500,36,15.59,C,C5,Fully Paid,105000.0,10,OWN,22.49,credit_card,CT,2,2016-08-01,0
539603,20000,20000,36,10.49,B,B3,Charged Off,84000.0,10,RENT,14.16,debt_consolidation,CO,2,2016-08-01,1
914066,28625,28625,60,11.49,B,B5,Fully Paid,98000.0,10,MORTGAGE,24.76,credit_card,CA,1,2016-10-01,0
1051749,15000,15000,60,9.99,B,B3,Fully Paid,65000.0,10,MORTGAGE,23.20,credit_card,IL,1,2015-10-01,0
571016,18000,18000,36,11.49,B,B5,Fully Paid,220000.0,10,MORTGAGE,8.28,home_improvement,WA,0,2016-07-01,0
1708664,20000,20000,36,23.40,E,E5,Fully Paid,125000.0,7,RENT,12.70,debt_consolidation,VA,1,2013-10-01,0

*Se exporta el dataset.*

In [31]:
df_modelo.to_csv('lending_club_limpio.csv', index=False)
print('CSV guardado.')
df_modelo.shape

CSV guardado.

(1230327, 16)